### ISSUE TITLE
Segfault when accessing playlists

### ISSUE THREAD

**Issue by pgrandin** [pgrandin/navit#1]
```
#0  0x00007f9383ee7e67 in waitpid () from /lib64/libc.so.6
#1  0x00007f9383e6fc50 in ?? () from /lib64/libc.so.6
#2  0x00007f9383e70010 in system () from /lib64/libc.so.6
#3  0x0000000000426236 in sigsegv (sig=<optimized out>) at /home/navit/navit/navit/navit/debug.c:83
#4  <signal handler called>
#5  0x00007f9383f7bc41 in ?? () from /lib64/libc.so.6
#6  0x00007f9385ad1d40 in g_strdup () from /usr/lib64/libglib-2.0.so.0
#7  0x00007f937d6d3c6a in gui_internal_text_font_new (this=this@entry=0xaac430, text=text@entry=0xffffffff84ad3ecc <Address 0xffffffff84ad3ecc out of bounds>, font=0, flags=flags@entry=131090)
    at /home/navit/navit/navit/navit/gui/internal/gui_internal_widget.c:148
#8  0x00007f937d6d3d3b in gui_internal_button_font_new_with_callback (this=this@entry=0xaac430, text=0xffffffff84ad3ecc <Address 0xffffffff84ad3ecc out of bounds>, font=font@entry=0, image=image@entry=0xd85c60, flags=flags@entry=66065,
    func=func@entry=0x7f937d6d7610 <spotify_play_playlist>, data=data@entry=0x0) at /home/navit/navit/navit/navit/gui/internal/gui_internal_widget.c:176
#9  0x00007f937d6d3df8 in gui_internal_button_new_with_callback (this=this@entry=0xaac430, text=<optimized out>, image=image@entry=0xd85c60, flags=flags@entry=66065, func=func@entry=0x7f937d6d7610 <spotify_play_playlist>,
    data=data@entry=0x0) at /home/navit/navit/navit/navit/gui/internal/gui_internal_widget.c:193
#10 0x00007f937d6d71a8 in gui_internal_spotify_show_rootlist (this=0xaac430, wm=<optimized out>, data=<optimized out>) at /home/navit/navit/navit/navit/gui/internal/gui_internal_spotify.c:226
#11 0x00007f937d6c7a58 in gui_internal_button (data=0xaac430, pressed=0, button=1, p=0x7fff5f856010) at /home/navit/navit/navit/navit/gui/internal/gui_internal.c:2593
#12 0x0000000000420db0 in callback_list_call_attr (l=0xffffffff84ad3ecc, type=attr_button, pcount=3, p=0x7fff5f855f80) at /home/navit/navit/navit/navit/callback.c:229
#13 0x0000000000420e6e in callback_list_call_attr_args (cbl=<optimized out>, type=type@entry=attr_button, count=count@entry=3) at /home/navit/navit/navit/navit/callback.c:245
#14 0x00007f938230f0bd in button_release (widget=<optimized out>, event=0xd1c0e0, user_data=0xaa88d0) at /home/navit/navit/navit/navit/graphics/gtk_drawing_area/graphics_gtk_drawing_area.c:818
#15 0x00007f9381ba76e9 in ?? () from /usr/lib64/libgtk-x11-2.0.so.0
#16 0x00007f9382d4b380 in g_closure_invoke () from /usr/lib64/libgobject-2.0.so.0
#17 0x00007f9382d5d4a0 in ?? () from /usr/lib64/libgobject-2.0.so.0
#18 0x00007f9382d64ebf in g_signal_emit_valist () from /usr/lib64/libgobject-2.0.so.0
#19 0x00007f9382d654a2 in g_signal_emit () from /usr/lib64/libgobject-2.0.so.0
#20 0x00007f9381cbfc5e in ?? () from /usr/lib64/libgtk-x11-2.0.so.0
#21 0x00007f9381ba5a54 in gtk_propagate_event () from /usr/lib64/libgtk-x11-2.0.so.0
#22 0x00007f9381ba5dbb in gtk_main_do_event () from /usr/lib64/libgtk-x11-2.0.so.0
#23 0x00007f93818154cc in ?? () from /usr/lib64/libgdk-x11-2.0.so.0
#24 0x00007f9385ab5664 in g_main_context_dispatch () from /usr/lib64/libglib-2.0.so.0
#25 0x00007f9385ab5898 in ?? () from /usr/lib64/libglib-2.0.so.0
#26 0x00007f9385ab5bb2 in g_main_loop_run () from /usr/lib64/libglib-2.0.so.0
#27 0x0000000000414fb5 in main_real (argc=<optimized out>, argv=<optimized out>) at /home/navit/navit/navit/navit/start_real.c:233
#28 0x00007f9383e4fbf5 in __libc_start_main () from /lib64/libc.so.6
#29 0x0000000000414421 in _start ()
```

**Comment by pgrandin** [comment]
Was caused by a broken playlist in spotify.
The playlist should show as "loading" in the official spotify player. Deleting the playlist solved the issue.
